[template]
src = 'paste.ini'
dest = '/etc/vouch/paste.ini'
owner = 'root'
mode = '0644'
keys = [
    '/fqdn',
    '/vouch',
    '/regions',
]
reload_cmd = 'supervisorctl -c /etc/supervisord-keystone.conf restart vouch'
