[template]
src = 'vouch-noauth.conf'
dest = '/etc/vouch/vouch-noauth.conf'
owner = 'root'
mode = '0644'
keys = [
    '/fqdn',
    '/vouch',
]
reload_cmd = 'supervisorctl -c /etc/supervisord-keystone.conf restart vouch'
